# REF: https://github.com/marketplace/actions/build-and-push-docker-images

name: Publish to DockerHub and GitHub

on:
  push:
    branches: main
    tags:
      - 'v*.*.*'

jobs:
  multi-registries:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Docker meta
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: name/app # list of Docker images to use as base name for tags
          tag-sha: true # add git short SHA as Docker tag
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64,linux/ppc64le,linux/s390x
          push: true
          tags: |
            jonasbn/ghcr-action-proto:latest
            jonasbn/ghcr-action-proto:${{ steps.docker_meta.outputs.tags }}
            ghcr.io/jonasbn/ghcr-action-proto:latest
            ghcr.io/jonasbn/ghcr-action-proto:${{ steps.docker_meta.outputs.tags }}
      # The Action supports publishing the README to DockerHub
      # REF: https://github.com/marketplace/actions/build-and-push-docker-images#update-dockerhub-repo-description
      # Using a 3rd. party action extension
      # REF: https://github.com/peter-evans/dockerhub-description
      # Unfortunately this does not work due to the security model with DockerHub
      # and the use of patch, please see issue below
      # REF: https://github.com/peter-evans/dockerhub-description/issues/10
      #-
      #  name: Update repository description on DockerHub
      #  uses: peter-evans/dockerhub-description@v2
      #  with:
      #    username: ${{ secrets.DOCKERHUB_USERNAME }}
      #    password: ${{ secrets.DOCKERHUB_TOKEN }}
      #    repository: jonasbn/ghcr-action-proto
